// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mission06_nj236.Models;

namespace Mission06_nj236.Migrations
{
    [DbContext(typeof(MovieDBContext))]
    partial class MovieDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.32");

            modelBuilder.Entity("Mission06_nj236.Models.MovieInfo", b =>
                {
                    b.Property<int>("MovieID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Edited")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LentTo")
                        .HasColumnType("TEXT");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("Rating")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Year")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("MovieID");

                    b.ToTable("MovieInfos");

                    b.HasData(
                        new
                        {
                            MovieID = 1,
                            Category = "Animated",
                            Director = "Brad Bird",
                            Edited = false,
                            LentTo = "",
                            Notes = "Prepare to cry",
                            Rating = "PG",
                            Title = "The Iron Giant",
                            Year = "1999"
                        },
                        new
                        {
                            MovieID = 2,
                            Category = "Action/Adventure",
                            Director = "Christopher Nolan",
                            Edited = false,
                            LentTo = "",
                            Notes = "Inversion",
                            Rating = "PG-13",
                            Title = "TENET",
                            Year = "2020"
                        },
                        new
                        {
                            MovieID = 3,
                            Category = "Drama",
                            Director = "Sidney Lumet",
                            Edited = false,
                            LentTo = "Nate J",
                            Notes = "",
                            Rating = "G",
                            Title = "12 Angry Men",
                            Year = "1957"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
